### ISSUE TITLE
Binding to `M-:` instead of remapping

### ISSUE THREAD

**Issue by Fuco1** [thierryvolpiatto/eldoc-eval#2]
Hi. I've remapped eval expression to `C-;` because it's much easier to type. I have other function on `M-:` (which I don't use all that often). This mode binds to it the `eldoc-eval-...` instead. I don't see any reason why a remap shouldn't be used.

**Comment by myeffort** [comment]
Might also consider introduced in 24.4 variable: eval-expression-minibuffer-setup-hook

**Comment by Fuco1** [comment]
That should probably go to a different issue. This here is solved.
