### ISSUE TITLE
please add a version tag so that it can be installed from melpa-stable

### ISSUE THREAD

**Issue by ruiyang** [thierryvolpiatto/eldoc-eval#3]
Hi,

I usually install packages from melpa-stable. could you please add a git tag with some version string like 0.1.0, so I could just install it from melpa-stable.

Thanks

**Comment by thierryvolpiatto** [comment]
Rui <notifications@github.com> writes:

> Hi,
>
> I usually install packages from melpa-stable. could you please add a
> git tag with some version string like 0.1.0, so I could just install
> it from melpa-stable.

Done.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by vjoki** [comment]
Could you also update the `Version:` comment, and close this issue while you're at it? :^)

**Comment by thierryvolpiatto** [comment]
I have removed :version which is not needed anymore nowaday.

**Comment by vjoki** [comment]
Thanks.
