### ISSUE TITLE
Shows function name in modeline, but not function params

### ISSUE THREAD

**Issue by analyticd** [thierryvolpiatto/eldoc-eval#7]
Perhaps it is just my config, but nevertheless. Emacs 26.2. Say I enter `(string-match-p` in the minibuffer, the modeline updates with the function name, but does not show any params as you would normally see. Any ideas?

**Comment by thierryvolpiatto** [comment]
Here it is working as expected with just `(eldoc-in-minibuffer-mode 1)`.
![Capture d’écran_2020-01-24_08-25-20](https://user-images.githubusercontent.com/1533939/73051928-2ecccb80-3e84-11ea-9447-9ea95306e63f.png)

Where did you get eldoc-eval? I maintain only the Melpa version, the Elpa version is broken IIRC.

**Comment by analyticd** [comment]
Thanks for checking this so quick. Hm, I was using a fresh copy from melpa from just now and it exhibits the problem. I then tried the version from github and same thing. Must be a configuration issue on my end if it works for you.
